language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then pyrus install pecl/redis && pyrus build pecl/redis; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"extension=redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = \"hhvm\" ]; then composer require --dev mongofill/mongofill=dev-master --no-update; fi"
  - "composer require --dev phpspec/phpspec:~2.0 --no-update"
  - "composer install --no-progress --no-plugins"
  - mysql -e "CREATE DATABASE bernard_test;"
  - psql -c 'CREATE DATABASE bernard_test;' -U postgres

script:
  - phpunit
  - phpunit --group functional
  - php vendor/bin/phpspec run
