language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - MONGO_VERSION=1.2.12
  - MONGO_VERSION=1.3.2
  - MONGO_VERSION=1.4.4

services: mongodb

before_script:
  - pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then pyrus install pecl/redis && pyrus build pecl/redis; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then echo \"extension=redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - "composer require --dev phpspec/phpspec:~2.0 --no-update"
  - "composer install --no-progress --no-plugins"

script:
  - phpunit
  - php vendor/bin/phpspec run
