sudo: false
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache/files

services: mongodb

before_script:
  - tests/travis.sh

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpunit --group functional
  - php vendor/bin/phpspec run
