language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_script:
  - tests/travis.sh

script:
  - phpunit
  - phpunit --group functional
  - php vendor/bin/phpspec run
